import type { ActivityType, ActivityConfig } from './types'

export interface ActivityTemplate {
  id: string
  title: string
  type: ActivityType
  discipline: string
  description: string
  config: ActivityConfig
}

export const DISCIPLINES = [
  'Political Science',
  'Philosophy & Ethics',
  'Law',
  'Business & Economics',
  'Medicine & Public Health',
  'STEM',
  'General',
] as const

export const TEMPLATES: ActivityTemplate[] = [
  // ═══ POLITICAL SCIENCE ═══
  {
    id: 'cuban-missile-negotiation',
    title: 'Cuban Missile Crisis Negotiation',
    type: 'scenario_multi',
    discipline: 'Political Science',
    description: 'Students play JFK navigating the crisis with Khrushchev, the Joint Chiefs, and the UN Secretary-General. Each stakeholder has competing interests.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Apply crisis decision-making frameworks', 'Navigate competing stakeholder demands', 'Practise strategic communication under pressure'],
      scenario_context: 'October 1962. U-2 reconnaissance photographs have confirmed Soviet nuclear missile installations in Cuba, 90 miles from Florida. The missiles will be operational within two weeks. The world does not yet know. You must decide how to respond before the missiles become active — and before the Soviets know you know.',
      student_role: 'President John F. Kennedy. You must protect American security while avoiding nuclear war. Your credibility, the Western alliance, and 200 million American lives are at stake.',
      ai_personas: [
        { name: 'Nikita Khrushchev', role: 'Premier of the Soviet Union', goals: 'Protect Soviet prestige. Keep the missiles if possible. Avoid nuclear war, but do not appear weak.', personality: 'Blunt, theatrical, alternates between folksy warmth and cold threats. Uses metaphors about farmers and weapons.' },
        { name: 'General Curtis LeMay', role: 'Air Force Chief of Staff and member of the Joint Chiefs', goals: 'Push for immediate air strikes on the missile sites. Sees diplomacy as weakness. Wants to eliminate the Soviet threat decisively.', personality: 'Aggressive, dismissive of diplomatic options, speaks in blunt military terms. Deeply patriotic.' },
        { name: 'U Thant', role: 'Secretary-General of the United Nations', goals: 'Prevent escalation. Propose a diplomatic off-ramp acceptable to both sides. Preserve the UN as a credible mediator.', personality: 'Calm, measured, formal. Appeals to international law and shared humanity.' },
      ],
      max_turns: 6,
      evaluation_rubric: ['Strategic reasoning', 'Stakeholder management', 'De-escalation skill', 'Historical plausibility'],
    },
  },
  {
    id: 'democratic-backsliding',
    title: 'Democratic Backsliding Debate',
    type: 'peer_critique',
    discipline: 'Political Science',
    description: 'Students argue whether a specific country is experiencing democratic backsliding, then critique a peer\'s analysis.',
    config: {
      rounds: 3,
      round_duration_sec: 300,
      initial_prompt: 'Choose one country that you believe is currently experiencing democratic backsliding. State your case: what specific institutional changes, policy actions, or norm violations constitute backsliding? Use at least one theoretical framework (Levitsky & Ziblatt, Bermeo, or Lührmann & Lindberg) to support your argument.',
      learning_objectives: ['Apply democratic erosion frameworks to real cases', 'Distinguish backsliding from normal democratic contestation', 'Construct and defend an evidence-based argument'],
      critique_prompt: 'Read your peer\'s analysis of democratic backsliding. Identify the weakest link in their causal chain — where does their evidence most fail to support their conclusion?',
      rebuttal_prompt: 'Your peer has identified a weakness in your argument. Respond directly: either concede and reformulate, or defend with additional evidence.',
    },
  },
  {
    id: 'foreign-policy-advisor',
    title: 'Foreign Policy Crisis Briefing',
    type: 'scenario_solo',
    discipline: 'Political Science',
    description: 'Students brief a head of state on an unfolding international crisis. The AI plays a sceptical national security advisor.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Apply IR theories to policy recommendations', 'Communicate under time pressure', 'Anticipate counterarguments from realist, liberal, and constructivist perspectives'],
      scenario_context: 'A neighbouring country has just conducted a military incursion into a disputed border region. Three of your citizens — aid workers — are trapped in the conflict zone. The UN Security Council is meeting in 6 hours. Your country has a mutual defence treaty with the invaded state, but your largest trading partner is backing the aggressor. The media is demanding a response.',
      student_role: 'Foreign Minister. You are briefing the Prime Minister. You must recommend a course of action and justify it.',
      ai_personas: [
        { name: 'Dr. Chen', role: 'National Security Advisor', goals: 'Stress-test every recommendation. Demand specifics. Push back on vague appeals to principles — insist on concrete costs, risks, and timelines.', personality: 'Sharp, impatient, deeply experienced. Asks uncomfortable follow-up questions. Respects clear thinking but has no patience for hand-waving.' },
      ],
      max_turns: 5,
      evaluation_rubric: ['Policy coherence', 'Risk assessment', 'Theoretical grounding', 'Communication clarity'],
    },
  },
  {
    id: 'electoral-systems',
    title: 'Electoral Systems Evidence Analysis',
    type: 'evidence_analysis',
    discipline: 'Political Science',
    description: 'Students interpret election data they haven\'t seen before and identify inferential gaps in a peer\'s analysis.',
    config: {
      rounds: 2,
      round_duration_sec: 300,
      initial_prompt: 'A country recently switched from first-past-the-post to mixed-member proportional representation. In the first election under the new system, the number of parties in parliament increased from 3 to 7, but voter turnout dropped from 72% to 58%. The largest party\'s seat share fell from 54% to 31%. What does this evidence tell us — and what does it NOT tell us — about the relationship between electoral systems and representation?',
      learning_objectives: ['Interpret electoral data critically', 'Distinguish correlation from causation in institutional analysis', 'Identify what evidence would be needed to support causal claims'],
      gap_prompt: 'Read your classmate\'s interpretation. Where do they make the biggest unsupported inferential leap — claiming the data shows something it cannot show on its own?',
    },
  },
  // ═══ PHILOSOPHY & ETHICS ═══
  {
    id: 'trolley-problem-extended',
    title: 'Trolley Problem: Extended Inquiry',
    type: 'socratic_chain',
    discipline: 'Philosophy & Ethics',
    description: 'Students state their position on the trolley problem, then face increasingly challenging AI-generated follow-ups that target gaps in their moral reasoning.',
    config: {
      rounds: 4,
      round_duration_sec: 240,
      initial_prompt: 'A runaway trolley will kill five people unless you pull a lever to divert it onto a side track, where it will kill one person. Do you pull the lever? State your position and the moral principle that justifies it.',
      learning_objectives: ['Articulate and defend a coherent moral position', 'Engage with consequentialist vs. deontological tensions', 'Recognise the limits of intuition-based moral reasoning'],
    },
  },
  {
    id: 'ai-ethics-stakeholders',
    title: 'AI Ethics Board Meeting',
    type: 'scenario_multi',
    discipline: 'Philosophy & Ethics',
    description: 'Students chair an AI ethics board reviewing a facial recognition deployment proposal. Stakeholders include a tech CEO, a civil rights attorney, and a police chief.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Balance competing ethical frameworks in applied contexts', 'Navigate stakeholder conflicts with incompatible values', 'Make and justify a policy recommendation'],
      scenario_context: 'Your city council is considering a proposal to deploy real-time facial recognition cameras in the downtown district. The system would be operated by police and powered by a private tech company. Crime in the area has risen 23% in two years. A recent audit of the same technology in another city found a 34% false positive rate for Black faces vs. 2% for white faces. You are chairing the ethics review board. You must hear from all stakeholders and make a recommendation to the council.',
      student_role: 'Chair of the Municipal AI Ethics Board. You must hear all perspectives and reach a recommendation — deploy, reject, or deploy with conditions.',
      ai_personas: [
        { name: 'Maya Torres', role: 'CEO of VisionAI, the technology provider', goals: 'Secure the contract. Emphasise accuracy improvements. Downplay bias concerns as fixable. Offer concessions if pressed.', personality: 'Polished, data-driven, deflects criticism with statistics and future promises.' },
        { name: 'James Washington', role: 'Civil rights attorney representing community groups', goals: 'Block deployment entirely. Centre racial bias data. Argue that no technical fix addresses the structural problem.', personality: 'Passionate, evidence-based, uses legal precedent. Personally affected — his teenage son was stopped by police last month.' },
        { name: 'Chief Patricia Hernandez', role: 'Police Chief', goals: 'Get the technology deployed. Acknowledge bias concerns but argue the public safety crisis justifies action. Open to oversight conditions.', personality: 'Pragmatic, direct, sympathetic to community concerns but frustrated by rising crime. Data-oriented.' },
      ],
      max_turns: 6,
      evaluation_rubric: ['Ethical reasoning depth', 'Fairness to all perspectives', 'Quality of final recommendation', 'Handling of conflicting evidence'],
    },
  },
  {
    id: 'justice-fairness',
    title: 'Distributive Justice Debate',
    type: 'peer_critique',
    discipline: 'Philosophy & Ethics',
    description: 'Students defend a theory of distributive justice, then identify the weakest assumption in a peer\'s argument.',
    config: {
      rounds: 3,
      round_duration_sec: 300,
      initial_prompt: 'A society must decide how to distribute a newly discovered resource that could either (a) be distributed equally to all citizens, (b) be given to those who need it most, or (c) be auctioned to generate revenue for public services. Which approach is most just, and why? Ground your argument in at least one philosophical framework (Rawls, Nozick, Sen, or another theorist of your choice).',
      learning_objectives: ['Apply theories of distributive justice to a concrete scenario', 'Distinguish between equality, equity, and efficiency', 'Construct and defend a normative argument'],
      critique_prompt: 'Read your peer\'s argument for their preferred distribution. What is the strongest objection from a rival theory of justice?',
      rebuttal_prompt: 'Your peer has raised an objection grounded in a rival theory. Respond: does your framework have an answer, or must you concede the point?',
    },
  },
  // ═══ LAW ═══
  {
    id: 'constitutional-rights',
    title: 'Constitutional Rights Moot',
    type: 'peer_critique',
    discipline: 'Law',
    description: 'Students argue for or against a constitutional challenge, then deconstruct a peer\'s legal reasoning.',
    config: {
      rounds: 3,
      round_duration_sec: 360,
      initial_prompt: 'A state has passed a law requiring all social media users to verify their identity using government-issued ID before posting. A coalition of users challenges the law as unconstitutional. You are arguing FOR the plaintiffs (the users). Construct your strongest constitutional argument for why this law should be struck down.',
      learning_objectives: ['Construct a constitutional argument with proper doctrinal grounding', 'Identify and attack weak legal reasoning', 'Respond to opposing arguments under time pressure'],
      critique_prompt: 'Read the opposing counsel\'s constitutional argument. Identify the weakest legal link — where does doctrine most fail to support their conclusion?',
      rebuttal_prompt: 'Opposing counsel has attacked your argument. Shore up the weakness they identified, or concede and reformulate with a stronger doctrinal foundation.',
    },
  },
  {
    id: 'contract-negotiation',
    title: 'Contract Negotiation',
    type: 'scenario_solo',
    discipline: 'Law',
    description: 'Students negotiate a commercial contract with an opposing counsel AI who pushes back on every clause.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Apply contract law principles in a practical negotiation', 'Balance client interests with realistic compromise', 'Draft precise contractual language under pressure'],
      scenario_context: 'Your client, a mid-size software company, is licensing its flagship product to a large hospital chain. The hospital wants a 5-year exclusive licence with unlimited users. Your client wants a 2-year non-exclusive licence with per-seat pricing. Key sticking points: liability caps, data ownership, termination clauses, and indemnification. Both sides want the deal — but not at any price.',
      student_role: 'Outside counsel representing the software company. Negotiate the best possible terms for your client while keeping the deal alive.',
      ai_personas: [
        { name: 'Sarah Okonkwo', role: 'General Counsel for the hospital chain', goals: 'Secure the longest possible exclusive licence at the lowest cost. Push for unlimited liability on data breaches. Resist per-seat pricing. Willing to compromise on term length if exclusivity is maintained.', personality: 'Experienced, methodical, never concedes a point without extracting something in return. Cordial but relentless.' },
      ],
      max_turns: 6,
      evaluation_rubric: ['Legal precision', 'Negotiation strategy', 'Client interest protection', 'Deal preservation'],
    },
  },
  // ═══ BUSINESS & ECONOMICS ═══
  {
    id: 'market-entry-strategy',
    title: 'Market Entry Strategy Pitch',
    type: 'scenario_solo',
    discipline: 'Business & Economics',
    description: 'Students pitch a market entry strategy to a sceptical venture capital partner who stress-tests every assumption.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Apply market analysis frameworks (Porter, PESTEL)', 'Defend strategic choices under scrutiny', 'Communicate business strategy concisely'],
      scenario_context: 'You are the founder of a health-tech startup that has built an AI-powered mental health screening tool. It works — clinical trials show 89% accuracy in detecting early signs of depression and anxiety in university students. You currently operate in Australia. You are pitching a Southeast Asian expansion to a VC partner who specialises in APAC health-tech. The partner has seen 200 pitches this quarter and has funded 3.',
      student_role: 'Startup founder pitching your Southeast Asian market entry strategy. You need $2M in Series A funding.',
      ai_personas: [
        { name: 'Priya Ramanathan', role: 'Partner at Meridian Ventures, APAC health-tech fund', goals: 'Find holes in the strategy. Test regulatory knowledge. Push on unit economics and cultural adaptation. Will invest if genuinely convinced, but defaults to scepticism.', personality: 'Direct, fast-paced, cuts through buzzwords. Asks follow-ups on any number you cite. Respects founders who say "I don\'t know" over those who bluff.' },
      ],
      max_turns: 5,
      evaluation_rubric: ['Market analysis depth', 'Financial reasoning', 'Regulatory awareness', 'Communication under pressure'],
    },
  },
  {
    id: 'supply-chain-crisis',
    title: 'Supply Chain Disruption Response',
    type: 'scenario_multi',
    discipline: 'Business & Economics',
    description: 'Students manage a supply chain crisis with competing demands from operations, finance, and a major retail client.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Apply operations management under crisis conditions', 'Balance short-term costs against long-term relationships', 'Make decisions with incomplete information'],
      scenario_context: 'Your consumer electronics company just learned that a fire at your primary semiconductor supplier in Taiwan has destroyed 60% of their production capacity. Your next product launch is in 8 weeks. You have inventory for 3 weeks of current orders. Your largest retail client (40% of revenue) is demanding guarantees that launch-day stock will be available. A secondary supplier can provide chips at 2.5x the cost with 6-week lead time. Your board meets in 2 hours and expects a plan.',
      student_role: 'VP of Operations. You must present a crisis response plan that satisfies all stakeholders — or explain the trade-offs honestly.',
      ai_personas: [
        { name: 'David Park', role: 'CFO', goals: 'Protect margins. Resist any plan that erodes Q3 earnings by more than 15%. Push for cost-cutting alternatives before expensive solutions.', personality: 'Analytical, risk-averse, speaks in numbers. Sympathetic but won\'t approve spending without a clear ROI case.' },
        { name: 'Lisa Chen', role: 'VP of Sales and key relationship manager for MegaMart (your largest client)', goals: 'Protect the MegaMart relationship at almost any cost. Losing this client means losing 40% of revenue. Push for whatever solution guarantees launch-day stock.', personality: 'Urgent, relationship-focused, willing to sacrifice margin for reliability. Gets emotional about client commitments.' },
        { name: 'Tom Nakamura', role: 'Head of Manufacturing', goals: 'Be realistic about what\'s physically possible. Push back on timelines that can\'t be met. Advocate for partial launch with limited SKUs.', personality: 'Calm, engineering-minded, speaks in specifics. Won\'t promise what he can\'t deliver.' },
      ],
      max_turns: 6,
      evaluation_rubric: ['Decision quality', 'Stakeholder management', 'Cost-benefit analysis', 'Communication clarity'],
    },
  },
  {
    id: 'economic-policy',
    title: 'Economic Policy Debate',
    type: 'peer_critique',
    discipline: 'Business & Economics',
    description: 'Students argue for a specific policy response to inflation, then attack a peer\'s economic reasoning.',
    config: {
      rounds: 3,
      round_duration_sec: 300,
      initial_prompt: 'A country is experiencing 8% annual inflation, 4.2% unemployment, and 1.1% GDP growth. The central bank\'s policy rate is currently 3.5%. What should the central bank do, and why? Ground your argument in a specific macroeconomic framework and address the trade-offs your preferred policy creates.',
      learning_objectives: ['Apply macroeconomic models to policy decisions', 'Reason about trade-offs between inflation and employment', 'Construct and defend a policy argument with evidence'],
      critique_prompt: 'Read your peer\'s policy recommendation. Where is the weakest economic assumption — the place where their model most diverges from likely reality?',
      rebuttal_prompt: 'Your peer has identified a weakness in your economic reasoning. Respond with evidence or concede and modify your recommendation.',
    },
  },
  // ═══ MEDICINE & PUBLIC HEALTH ═══
  {
    id: 'patient-consultation',
    title: 'Difficult Patient Consultation',
    type: 'scenario_solo',
    discipline: 'Medicine & Public Health',
    description: 'Students navigate a difficult patient conversation about treatment options with an anxious, well-informed patient.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Practise patient-centred communication', 'Explain medical uncertainty honestly', 'Navigate informed consent with a challenging patient'],
      scenario_context: 'Your patient, Margaret (62), has been diagnosed with stage II breast cancer. Imaging and biopsy results are in. The oncology team recommends surgery followed by chemotherapy. However, Margaret has been researching immunotherapy trials online and is resistant to chemotherapy. Her sister died of cancer last year after a difficult course of chemo. Margaret is intelligent, anxious, and has a list of questions from medical websites.',
      student_role: 'Oncology registrar. This is your consultation to explain the treatment plan, address Margaret\'s concerns, and help her make an informed decision. You must not dismiss her research, but you must be honest about what the evidence shows.',
      ai_personas: [
        { name: 'Margaret', role: 'Patient, 62, retired teacher', goals: 'Understand her options honestly. Avoid chemotherapy if at all possible. Find out about immunotherapy trials. Feel heard, not dismissed. Will push back if she feels patronised.', personality: 'Intelligent, anxious but composed, has done extensive research (some accurate, some misleading). Values honesty over reassurance. Gets upset if she feels her questions are being deflected.' },
      ],
      max_turns: 6,
      evaluation_rubric: ['Empathy and rapport', 'Medical accuracy', 'Shared decision-making', 'Handling of uncertainty'],
    },
  },
  {
    id: 'public-health-crisis',
    title: 'Public Health Emergency Response',
    type: 'scenario_multi',
    discipline: 'Medicine & Public Health',
    description: 'Students lead the response to a disease outbreak with competing advice from epidemiology, politics, and media.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Apply epidemiological reasoning under uncertainty', 'Balance public health with economic and political constraints', 'Communicate risk to diverse audiences'],
      scenario_context: 'A novel respiratory illness has appeared in your city (population: 2 million). In the past 10 days: 340 confirmed cases, 12 deaths, 28 in ICU. The pathogen has been identified but no vaccine exists. Transmission appears airborne. Two schools and a nursing home have reported clusters. It\'s exam season at the universities and the holiday shopping period begins next week. The mayor wants a recommendation by end of day.',
      student_role: 'Chief Public Health Officer. You must recommend a response strategy and justify it to all stakeholders.',
      ai_personas: [
        { name: 'Dr. Amira Hassan', role: 'Chief Epidemiologist', goals: 'Push for aggressive containment: school closures, gathering limits, mask mandates. Prioritise R0 reduction. Worried about ICU capacity.', personality: 'Data-driven, cautious, speaks in epidemiological terms. Frustrated when non-scientists dismiss modelling.' },
        { name: 'Councillor James Whitfield', role: 'Deputy Mayor and economic development lead', goals: 'Minimise economic disruption. Resist closures during the holiday period. Push for targeted rather than blanket measures.', personality: 'Politically savvy, genuinely concerned about livelihoods, not just optics. Will compromise if shown the data.' },
        { name: 'Rachel Kim', role: 'Senior health reporter at the city\'s largest newspaper', goals: 'Get straight answers for the public. Will publish whatever she hears. Pushes hard on what officials aren\'t saying.', personality: 'Persistent, fair but adversarial. Asks the question the public is thinking. Respects transparency, punishes evasion.' },
      ],
      max_turns: 6,
      evaluation_rubric: ['Epidemiological reasoning', 'Policy proportionality', 'Risk communication', 'Stakeholder management'],
    },
  },
  // ═══ STEM ═══
  {
    id: 'climate-data-analysis',
    title: 'Climate Data Interpretation',
    type: 'evidence_analysis',
    discipline: 'STEM',
    description: 'Students interpret unfamiliar climate data and identify inferential gaps in a peer\'s analysis.',
    config: {
      rounds: 2,
      round_duration_sec: 300,
      initial_prompt: 'A research team measured ocean surface temperatures at 50 stations in the North Atlantic over 30 years. They found a 1.2°C average increase, but with high variance: 15 stations showed cooling, 10 showed no change, and 25 showed warming (range: +0.3°C to +4.1°C). The team concludes: "The North Atlantic is warming." What does this evidence support, what does it not support, and what additional data would you need to evaluate their conclusion?',
      learning_objectives: ['Interpret scientific data with appropriate uncertainty', 'Distinguish between aggregate trends and local variation', 'Identify what evidence would strengthen or weaken a conclusion'],
      gap_prompt: 'Read your classmate\'s analysis of the ocean temperature data. Where do they make the biggest inferential leap — claiming the data shows something it cannot show without additional evidence?',
    },
  },
  {
    id: 'engineering-ethics',
    title: 'Engineering Ethics: Whistleblower Decision',
    type: 'socratic_chain',
    discipline: 'STEM',
    description: 'Students decide whether to blow the whistle on a safety concern, then face AI-generated challenges to their moral reasoning.',
    config: {
      rounds: 4,
      round_duration_sec: 240,
      initial_prompt: 'You are a junior structural engineer at a large construction firm. During a routine review, you notice that the load-bearing calculations for a 20-storey residential building under construction appear to use an outdated safety margin that no longer meets current code. Your senior engineer reviewed and approved the calculations. When you raised the issue informally, they said "it\'s fine, we\'ve always done it this way." The building is 60% complete. What do you do, and why?',
      learning_objectives: ['Apply engineering ethics frameworks to a realistic scenario', 'Reason about competing obligations (safety, loyalty, career)', 'Articulate the moral basis for a professional decision'],
    },
  },
  // ═══ GENERAL / CROSS-DISCIPLINE ═══
  {
    id: 'research-methods-confusion',
    title: 'Research Methods: Name Your Confusion',
    type: 'peer_clarification',
    discipline: 'General',
    description: 'Students articulate what they don\'t understand about research methods, then explain a classmate\'s confusion in plain language.',
    config: {
      rounds: 2,
      round_duration_sec: 300,
      initial_prompt: 'Think about the research methods you\'ve encountered this semester (experimental design, surveys, case studies, statistical inference, qualitative coding, etc.). Identify one specific concept or technique you don\'t yet understand well enough to explain to a friend outside your field. Describe precisely what confuses you — not just that it\'s confusing, but where your understanding breaks down.',
      learning_objectives: ['Develop metacognitive awareness of knowledge gaps', 'Practise peer explanation (the protégé effect)', 'Build shared understanding across different confusion points'],
      explain_prompt: 'A classmate has described their confusion below. Explain this concept to them in plain language, as if teaching a friend. No jargon, no textbook quotes — just your own understanding.',
    },
  },
  {
    id: 'source-evaluation',
    title: 'Source Evaluation Challenge',
    type: 'evidence_analysis',
    discipline: 'General',
    description: 'Students evaluate a set of conflicting sources on a controversial topic and identify where a peer\'s reasoning breaks down.',
    config: {
      rounds: 2,
      round_duration_sec: 300,
      initial_prompt: 'You are given three sources on the same topic:\n\n• Source A (peer-reviewed journal, 2023): "Remote work increases individual productivity by 13% but decreases team innovation output by 20%."\n• Source B (industry report by a co-working space company, 2024): "92% of employees prefer hybrid work. Companies with hybrid policies report 35% higher retention."\n• Source C (newspaper op-ed by a CEO, 2024): "The remote work experiment is over. My company\'s best ideas came from hallway conversations that Zoom cannot replicate."\n\nUsing these three sources, what can you confidently conclude about remote work\'s effect on organisational performance? What can you NOT conclude? Evaluate each source\'s credibility and limitations.',
      learning_objectives: ['Evaluate source credibility and bias', 'Synthesise conflicting evidence', 'Distinguish between evidence and opinion'],
      gap_prompt: 'Read your classmate\'s source evaluation. Where do they accept a source too uncritically, or dismiss one without sufficient justification?',
    },
  },
  {
    id: 'critical-reading',
    title: 'Critical Reading: Deepen Your Argument',
    type: 'socratic_chain',
    discipline: 'General',
    description: 'Students respond to a reading prompt, then face personalised AI follow-ups that push them to go deeper. Works with any assigned text.',
    config: {
      rounds: 3,
      round_duration_sec: 300,
      initial_prompt: 'Based on this week\'s assigned reading, identify the author\'s central argument and the single strongest piece of evidence they use to support it. Then: what is the most important thing the author\'s argument CANNOT explain?',
      learning_objectives: ['Identify core arguments in academic texts', 'Evaluate the scope and limits of an argument', 'Develop independent critical analysis'],
    },
  },
  {
    id: 'presentation-fear',
    title: 'Presentation Skills: Hostile Q&A',
    type: 'scenario_solo',
    discipline: 'General',
    description: 'Students practise defending their thesis/project against a tough but fair questioner. Great for presentation prep.',
    config: {
      rounds: 1,
      round_duration_sec: 600,
      initial_prompt: '',
      learning_objectives: ['Defend research under questioning', 'Handle hostile but legitimate questions', 'Think on your feet'],
      scenario_context: 'You have just presented your research project / thesis proposal to a panel. The presentation went well, but now comes the Q&A. The panel chair is known for asking difficult but fair questions. They have read your work carefully and will probe every weak point. This is your chance to demonstrate deep understanding of your own research.',
      student_role: 'Researcher defending your work. When the session starts, briefly state your research question and key finding in 2-3 sentences, then the panel chair will begin questioning.',
      ai_personas: [
        { name: 'Professor Okafor', role: 'Panel Chair, expert in your field', goals: 'Test the depth of the student\'s understanding. Ask about methodology, alternative explanations, limitations, and implications. Be tough but fair — give credit for honest answers.', personality: 'Intellectually rigorous, not unkind but does not let weak answers slide. Follows up relentlessly on vague claims. Appreciates precision and intellectual honesty.' },
      ],
      max_turns: 5,
      evaluation_rubric: ['Depth of understanding', 'Handling of criticism', 'Intellectual honesty', 'Clarity of communication'],
    },
  },
]
