-- Migration 008: Student-facing session summary
--
-- Adds:
--   1. ai_feedback TEXT column on participants — stores the per-student AI
--      feedback generated by the generate-feedback edge function, so students
--      can access it from their own device without instructor interaction.
--   2. get_participant_summary() — SECURITY DEFINER RPC that validates the
--      student token then returns their full session data in one call.

-- ============================================================
-- 1. Add ai_feedback column
-- ============================================================
ALTER TABLE participants
  ADD COLUMN IF NOT EXISTS ai_feedback TEXT;

-- ============================================================
-- 2. get_participant_summary
--    Called from the student-facing /session/:id/summary page.
--    Validates the token, then returns:
--      participant_name, ai_feedback,
--      session metadata (title, type, date, join_code),
--      all responses ordered by round,
--      all AI follow-up prompts (Socratic Chain)
-- ============================================================
CREATE OR REPLACE FUNCTION get_participant_summary(
  p_participant_id  UUID,
  p_token           TEXT,
  p_session_id      UUID
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_participant   RECORD;
  v_session       RECORD;
  v_responses     JSONB;
  v_follow_ups    JSONB;
BEGIN
  -- Validate token matches the participant in this session
  SELECT * INTO v_participant
  FROM participants
  WHERE id = p_participant_id
    AND token = p_token
    AND session_id = p_session_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid participant token' USING ERRCODE = 'P0001';
  END IF;

  -- Load session + activity metadata
  SELECT
    s.id,
    s.join_code,
    s.created_at,
    s.status,
    a.title  AS activity_title,
    a.type   AS activity_type,
    a.config AS activity_config
  INTO v_session
  FROM sessions s
  JOIN activities a ON a.id = s.activity_id
  WHERE s.id = p_session_id;

  -- Load this participant's responses in round order
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'round',          r.round,
        'content',        r.content,
        'response_type',  r.response_type,
        'time_taken_ms',  r.time_taken_ms,
        'submitted_at',   r.submitted_at
      ) ORDER BY r.round
    ),
    '[]'::jsonb
  ) INTO v_responses
  FROM responses r
  WHERE r.session_id     = p_session_id
    AND r.participant_id = p_participant_id;

  -- Load AI follow-up prompts (Socratic Chain)
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'round',  fu.round,
        'prompt', fu.prompt
      ) ORDER BY fu.round
    ),
    '[]'::jsonb
  ) INTO v_follow_ups
  FROM follow_ups fu
  WHERE fu.session_id     = p_session_id
    AND fu.participant_id = p_participant_id;

  RETURN jsonb_build_object(
    'participant_name',  v_participant.display_name,
    'ai_feedback',       v_participant.ai_feedback,
    'join_code',         v_session.join_code,
    'session_date',      v_session.created_at,
    'activity_title',    v_session.activity_title,
    'activity_type',     v_session.activity_type,
    'activity_config',   v_session.activity_config,
    'responses',         v_responses,
    'follow_ups',        v_follow_ups
  );
END;
$$;
