-- Migration 009: Scenario simulation activity support
--
-- Adds two tables:
--   1. scenario_messages — full per-participant chat transcript
--      (stores both student and AI turns)
--   2. scenario_evaluations — per-participant rubric-scored feedback
--      generated by the evaluate-scenario edge function
-- Also adds submit_scenario_message() SECURITY DEFINER RPC so students
-- can write to scenario_messages without direct table access.

-- ============================================================
-- 1. scenario_messages
-- ============================================================
CREATE TABLE IF NOT EXISTS scenario_messages (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  participant_id  UUID        NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  turn            INT         NOT NULL,
  speaker_type    TEXT        NOT NULL CHECK (speaker_type IN ('student', 'ai')),
  speaker_name    TEXT        NOT NULL,
  content         TEXT        NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS scenario_messages_session_idx
  ON scenario_messages (session_id);

CREATE INDEX IF NOT EXISTS scenario_messages_participant_idx
  ON scenario_messages (session_id, participant_id, turn);

-- ============================================================
-- 2. scenario_evaluations
-- ============================================================
CREATE TABLE IF NOT EXISTS scenario_evaluations (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  participant_id  UUID        NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  content         JSONB       NOT NULL,
  -- content shape: { scores: { reasoning, communication, evidence, ethics }, feedback: "..." }
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (session_id, participant_id)
);

CREATE INDEX IF NOT EXISTS scenario_evaluations_session_idx
  ON scenario_evaluations (session_id);

-- ============================================================
-- 3. RLS
-- ============================================================
ALTER TABLE scenario_messages    ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenario_evaluations ENABLE ROW LEVEL SECURITY;

-- Instructors can read messages for sessions they own
CREATE POLICY "Instructors can read scenario messages"
  ON scenario_messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM sessions s
      WHERE s.id = scenario_messages.session_id
        AND s.instructor_id = auth.uid()
    )
  );

-- Instructors can read evaluations for sessions they own
CREATE POLICY "Instructors can read scenario evaluations"
  ON scenario_evaluations FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM sessions s
      WHERE s.id = scenario_evaluations.session_id
        AND s.instructor_id = auth.uid()
    )
  );

-- No direct student writes — all writes go through the edge function
-- using the service role key (bypasses RLS).

-- ============================================================
-- 4. submit_scenario_message — called by the edge function
--    (kept here for documentation; actual inserts use service role)
-- ============================================================
-- Students read their own scenario messages via the edge function
-- response payload, so no additional SELECT policy is needed on the
-- client. The edge function returns the full updated transcript.

-- ============================================================
-- 5. get_scenario_transcript — SECURITY DEFINER helper used by
--    the student summary page for scenario sessions
-- ============================================================
CREATE OR REPLACE FUNCTION get_scenario_transcript(
  p_participant_id  UUID,
  p_token           TEXT,
  p_session_id      UUID
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_participant RECORD;
  v_messages    JSONB;
  v_eval        JSONB;
BEGIN
  SELECT * INTO v_participant
  FROM participants
  WHERE id = p_participant_id
    AND token = p_token
    AND session_id = p_session_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid participant token' USING ERRCODE = 'P0001';
  END IF;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'turn',         m.turn,
        'speaker_type', m.speaker_type,
        'speaker_name', m.speaker_name,
        'content',      m.content,
        'created_at',   m.created_at
      ) ORDER BY m.turn
    ),
    '[]'::jsonb
  ) INTO v_messages
  FROM scenario_messages m
  WHERE m.session_id     = p_session_id
    AND m.participant_id = p_participant_id;

  SELECT content INTO v_eval
  FROM scenario_evaluations
  WHERE session_id     = p_session_id
    AND participant_id = p_participant_id;

  RETURN jsonb_build_object(
    'messages',   v_messages,
    'evaluation', v_eval
  );
END;
$$;
